version: "3.8"
services:
         cms-app:
                container_name: Jenkins
                image: jenkins
                restart: unless-stopped
                build: .
                ports:
                  - "8080:8080"
                links:
                  - sonarqube
                volumes:
                  - jenkins-data_db_home:/opt/jenkins/db
                  - jenkins-data_jenkins_home:/home/jenkins
                  - /var/run/docker.sock:/var/run/docker.sock
                  - /usr/bin/docker:/usr/bin/docker
                networks:
                   vpcbr:
                     ipv4_address: 172.20.0.5
         sonarqube:
                container_name: sonarqube
                image: sonarqube
                depends_on:
                  - db
#                links:
#                  - db
                environment:
                  SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
                  SONAR_JDBC_USERNAME: sonar
                  SONAR_JDBC_PASSWORD: sonar
                volumes:
                  - sonarqube-data:/opt/sonarqube/data 
                  - sonarqube-extensions:/opt/sonarqube/extensions 
                  - sonarqube-logs:/opt/sonarqube/logs sonarqube 
                ports:
                  - "9000:9000"
                networks:
                   vpcbr:
                     ipv4_address: 172.20.0.6
         db:
             image: postgres:12
             ports:
                  - "5432:5432"
             environment:
                POSTGRES_USER: sonar
                POSTGRES_PASSWORD: sonar #tochange
             volumes:
                - postgresql:/var/lib/postgresql
                - postgresql_data:/var/lib/postgresql/data
             networks:
                   vpcbr:
                     ipv4_address: 172.20.0.7
 

volumes:
   sonarqube-data:
     external: true
   sonarqube-extensions:
     external: true
   sonarqube-logs:
     external: true
   jenkins-data_jenkins_home:
     external: true
   jenkins-data_db_home:
     external: true
   postgresql:
     external: true
   postgresql_data:
     external: true

networks:
  vpcbr:
     driver: bridge
     ipam: 
       config: 
         - subnet: 172.20.0.0/16
           gateway: 172.20.0.1
